# Generated by Django 4.2 on 2023-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_alter_variacao_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variável"), ("S", "Simples")], default="v", max_length=1
            ),
        ),
    ]
